import { SingleCard } from "../types";

export const CARD_VALUES = [
  "two",
  "three",
  "four",
  "five",
  "six",
  "seven",
  "eight",
  "nine",
  "ten",
  "jack",
  "queen",
  "king",
  "ace",
];

export const SUIT_RED_COLOR = "#b8000a";

export const SUIT_BLACK_COLOR = "#000000";

export const FULL_DECK: SingleCard[] = [
  { id: "2H", number: 2, suit: "HEARTS" },
  { id: "3H", number: 3, suit: "HEARTS" },
  { id: "4H", number: 4, suit: "HEARTS" },
  { id: "5H", number: 5, suit: "HEARTS" },
  { id: "6H", number: 6, suit: "HEARTS" },
  { id: "7H", number: 7, suit: "HEARTS" },
  { id: "8H", number: 8, suit: "HEARTS" },
  { id: "9H", number: 9, suit: "HEARTS" },
  { id: "TH", number: 10, suit: "HEARTS" },
  { id: "JH", number: 11, suit: "HEARTS" },
  { id: "QH", number: 12, suit: "HEARTS" },
  { id: "KH", number: 13, suit: "HEARTS" },
  { id: "AH", number: 14, suit: "HEARTS" },
  { id: "2D", number: 2, suit: "DIAMONDS" },
  { id: "3D", number: 3, suit: "DIAMONDS" },
  { id: "4D", number: 4, suit: "DIAMONDS" },
  { id: "5D", number: 5, suit: "DIAMONDS" },
  { id: "6D", number: 6, suit: "DIAMONDS" },
  { id: "7D", number: 7, suit: "DIAMONDS" },
  { id: "8D", number: 8, suit: "DIAMONDS" },
  { id: "9D", number: 9, suit: "DIAMONDS" },
  { id: "TD", number: 10, suit: "DIAMONDS" },
  { id: "JD", number: 11, suit: "DIAMONDS" },
  { id: "QD", number: 12, suit: "DIAMONDS" },
  { id: "KD", number: 13, suit: "DIAMONDS" },
  { id: "AD", number: 14, suit: "DIAMONDS" },
  { id: "2C", number: 2, suit: "CLUBS" },
  { id: "3C", number: 3, suit: "CLUBS" },
  { id: "4C", number: 4, suit: "CLUBS" },
  { id: "5C", number: 5, suit: "CLUBS" },
  { id: "6C", number: 6, suit: "CLUBS" },
  { id: "7C", number: 7, suit: "CLUBS" },
  { id: "8C", number: 8, suit: "CLUBS" },
  { id: "9C", number: 9, suit: "CLUBS" },
  { id: "TC", number: 10, suit: "CLUBS" },
  { id: "JC", number: 11, suit: "CLUBS" },
  { id: "QC", number: 12, suit: "CLUBS" },
  { id: "KC", number: 13, suit: "CLUBS" },
  { id: "AC", number: 14, suit: "CLUBS" },
  { id: "2S", number: 2, suit: "SPADES" },
  { id: "3S", number: 3, suit: "SPADES" },
  { id: "4S", number: 4, suit: "SPADES" },
  { id: "5S", number: 5, suit: "SPADES" },
  { id: "6S", number: 6, suit: "SPADES" },
  { id: "7S", number: 7, suit: "SPADES" },
  { id: "8S", number: 8, suit: "SPADES" },
  { id: "9S", number: 9, suit: "SPADES" },
  { id: "TS", number: 10, suit: "SPADES" },
  { id: "JS", number: 11, suit: "SPADES" },
  { id: "QS", number: 12, suit: "SPADES" },
  { id: "KS", number: 13, suit: "SPADES" },
  { id: "AS", number: 14, suit: "SPADES" },
];
