import { CardSuits, SingleCard } from "../types";

export const CARD_VALUES = [
  "ace",
  "two",
  "three",
  "four",
  "five",
  "six",
  "seven",
  "eight",
  "nine",
  "ten",
  "jack",
  "queen",
  "king",
];

export const SUIT_RED_COLOR = "#b8000a";

export const SUIT_BLACK_COLOR = "#000000";

export const FULL_DECK: SingleCard[] = [
  { number: 1, suit: "HEARTS" },
  { number: 2, suit: "HEARTS" },
  { number: 3, suit: "HEARTS" },
  { number: 4, suit: "HEARTS" },
  { number: 5, suit: "HEARTS" },
  { number: 6, suit: "HEARTS" },
  { number: 7, suit: "HEARTS" },
  { number: 8, suit: "HEARTS" },
  { number: 9, suit: "HEARTS" },
  { number: 10, suit: "HEARTS" },
  { number: 11, suit: "HEARTS" },
  { number: 12, suit: "HEARTS" },
  { number: 13, suit: "HEARTS" },
  { number: 1, suit: "DIAMONDS" },
  { number: 2, suit: "DIAMONDS" },
  { number: 3, suit: "DIAMONDS" },
  { number: 4, suit: "DIAMONDS" },
  { number: 5, suit: "DIAMONDS" },
  { number: 6, suit: "DIAMONDS" },
  { number: 7, suit: "DIAMONDS" },
  { number: 8, suit: "DIAMONDS" },
  { number: 9, suit: "DIAMONDS" },
  { number: 10, suit: "DIAMONDS" },
  { number: 11, suit: "DIAMONDS" },
  { number: 12, suit: "DIAMONDS" },
  { number: 13, suit: "DIAMONDS" },
  { number: 1, suit: "CLUBS" },
  { number: 2, suit: "CLUBS" },
  { number: 3, suit: "CLUBS" },
  { number: 4, suit: "CLUBS" },
  { number: 5, suit: "CLUBS" },
  { number: 6, suit: "CLUBS" },
  { number: 7, suit: "CLUBS" },
  { number: 8, suit: "CLUBS" },
  { number: 9, suit: "CLUBS" },
  { number: 10, suit: "CLUBS" },
  { number: 11, suit: "CLUBS" },
  { number: 12, suit: "CLUBS" },
  { number: 13, suit: "CLUBS" },
  { number: 1, suit: "SPADES" },
  { number: 2, suit: "SPADES" },
  { number: 3, suit: "SPADES" },
  { number: 4, suit: "SPADES" },
  { number: 5, suit: "SPADES" },
  { number: 6, suit: "SPADES" },
  { number: 7, suit: "SPADES" },
  { number: 8, suit: "SPADES" },
  { number: 9, suit: "SPADES" },
  { number: 10, suit: "SPADES" },
  { number: 11, suit: "SPADES" },
  { number: 12, suit: "SPADES" },
  { number: 13, suit: "SPADES" },
];
